apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-sample-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: application-sample-2
  name: component-sample-2
  namespace: maysun
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/instance: component-sample-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: component-sample-2
    spec:
      containers:
      - env:
        - name: FOO
          value: foo1
        - name: BAR
          value: bar1
        image: quay.io/myimage
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 4444
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 4444
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 4444
        resources:
          limits:
            cpu: "2"
            memory: 500Mi
            storage: 400Mi
          requests:
            cpu: 700m
            memory: 400Mi
            storage: 200Mi
status: {}
